### ISSUE TITLE
no-return-assign

### ISSUE THREAD

**Issue by Pholey** [launchbadge/eslint-config-launchbadge-browser#2]
> Arrow function should not return assignment

Use case (mutability with forEach): 

```
range.forEach((x) => el.style.transform = `translate3d(${x}px, 0, 0)`);
```

**Comment by mehcode** [comment]
Don't use `forEach`. The idiomatic approach is do:

```
for (const x of range) {
  x.style.transform = `translate3d(${x}px, 0, 0)`;
}
```

This also works with iterators and not just arrays.
